version: "3.1"
services:
  metabase:
    image: metabase/metabase:v0.50.10
    volumes:
      - ./include/metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - 3000:3000
    restart: always